// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgdqEXa_Qixzvi9q06jBgk9jEuzIXitok',
    appId: '1:196500997657:web:f0067876d794155e660c88',
    messagingSenderId: '196500997657',
    projectId: 'algorithmat-615cf',
    authDomain: 'algorithmat-615cf.firebaseapp.com',
    storageBucket: 'algorithmat-615cf.firebasestorage.app',
    measurementId: 'G-C3VDLEB1DB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALDLqfFAdADSlgUMelITevzMaX8FxJcIk',
    appId: '1:196500997657:android:eb27d950d25a11cf660c88',
    messagingSenderId: '196500997657',
    projectId: 'algorithmat-615cf',
    storageBucket: 'algorithmat-615cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzwYnlcirjs6GInQEhueeiGfwcXaCTiy0',
    appId: '1:196500997657:ios:9fdaa94c5f0ee9a0660c88',
    messagingSenderId: '196500997657',
    projectId: 'algorithmat-615cf',
    storageBucket: 'algorithmat-615cf.firebasestorage.app',
    iosBundleId: 'com.example.visualAlgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgdqEXa_Qixzvi9q06jBgk9jEuzIXitok',
    appId: '1:196500997657:web:dc5569b00430d7ee660c88',
    messagingSenderId: '196500997657',
    projectId: 'algorithmat-615cf',
    authDomain: 'algorithmat-615cf.firebaseapp.com',
    storageBucket: 'algorithmat-615cf.firebasestorage.app',
    measurementId: 'G-90TSEF9D4R',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgdqEXa_Qixzvi9q06jBgk9jEuzIXitok',
    appId: '1:196500997657:web:dc5569b00430d7ee660c88',
    messagingSenderId: '196500997657',
    projectId: 'algorithmat-615cf',
    authDomain: 'algorithmat-615cf.firebaseapp.com',
    storageBucket: 'algorithmat-615cf.firebasestorage.app',
    measurementId: 'G-90TSEF9D4R',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAgdqEXa_Qixzvi9q06jBgk9jEuzIXitok',
    appId: '1:196500997657:web:dc5569b00430d7ee660c88',
    messagingSenderId: '196500997657',
    projectId: 'algorithmat-615cf',
    authDomain: 'algorithmat-615cf.firebaseapp.com',
    storageBucket: 'algorithmat-615cf.firebasestorage.app',
    measurementId: 'G-90TSEF9D4R',
  );
}
